// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: frequent_flier_account.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_RED         Status = 1
	Status_STATUS_SILVER      Status = 2
	Status_STATUS_GOLD        Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_RED",
		2: "STATUS_SILVER",
		3: "STATUS_GOLD",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_RED":         1,
		"STATUS_SILVER":      2,
		"STATUS_GOLD":        3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_frequent_flier_account_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_frequent_flier_account_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_frequent_flier_account_proto_rawDescGZIP(), []int{0}
}

type FrequentFlierAccountEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to EventType:
	//
	//	*FrequentFlierAccountEvent_AccountCreated
	//	*FrequentFlierAccountEvent_StatusMatched
	//	*FrequentFlierAccountEvent_PromotedToGoldStatus
	//	*FrequentFlierAccountEvent_FlightTaken
	EventType     isFrequentFlierAccountEvent_EventType `protobuf_oneof:"event_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrequentFlierAccountEvent) Reset() {
	*x = FrequentFlierAccountEvent{}
	mi := &file_frequent_flier_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrequentFlierAccountEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrequentFlierAccountEvent) ProtoMessage() {}

func (x *FrequentFlierAccountEvent) ProtoReflect() protoreflect.Message {
	mi := &file_frequent_flier_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrequentFlierAccountEvent.ProtoReflect.Descriptor instead.
func (*FrequentFlierAccountEvent) Descriptor() ([]byte, []int) {
	return file_frequent_flier_account_proto_rawDescGZIP(), []int{0}
}

func (x *FrequentFlierAccountEvent) GetEventType() isFrequentFlierAccountEvent_EventType {
	if x != nil {
		return x.EventType
	}
	return nil
}

func (x *FrequentFlierAccountEvent) GetAccountCreated() *FrequentFlierAccountCreated {
	if x != nil {
		if x, ok := x.EventType.(*FrequentFlierAccountEvent_AccountCreated); ok {
			return x.AccountCreated
		}
	}
	return nil
}

func (x *FrequentFlierAccountEvent) GetStatusMatched() *StatusMatched {
	if x != nil {
		if x, ok := x.EventType.(*FrequentFlierAccountEvent_StatusMatched); ok {
			return x.StatusMatched
		}
	}
	return nil
}

func (x *FrequentFlierAccountEvent) GetPromotedToGoldStatus() *PromotedToGoldStatus {
	if x != nil {
		if x, ok := x.EventType.(*FrequentFlierAccountEvent_PromotedToGoldStatus); ok {
			return x.PromotedToGoldStatus
		}
	}
	return nil
}

func (x *FrequentFlierAccountEvent) GetFlightTaken() *FlightTaken {
	if x != nil {
		if x, ok := x.EventType.(*FrequentFlierAccountEvent_FlightTaken); ok {
			return x.FlightTaken
		}
	}
	return nil
}

type isFrequentFlierAccountEvent_EventType interface {
	isFrequentFlierAccountEvent_EventType()
}

type FrequentFlierAccountEvent_AccountCreated struct {
	AccountCreated *FrequentFlierAccountCreated `protobuf:"bytes,1,opt,name=account_created,json=accountCreated,proto3,oneof"`
}

type FrequentFlierAccountEvent_StatusMatched struct {
	StatusMatched *StatusMatched `protobuf:"bytes,2,opt,name=status_matched,json=statusMatched,proto3,oneof"`
}

type FrequentFlierAccountEvent_PromotedToGoldStatus struct {
	PromotedToGoldStatus *PromotedToGoldStatus `protobuf:"bytes,3,opt,name=promoted_to_gold_status,json=promotedToGoldStatus,proto3,oneof"`
}

type FrequentFlierAccountEvent_FlightTaken struct {
	FlightTaken *FlightTaken `protobuf:"bytes,4,opt,name=flight_taken,json=flightTaken,proto3,oneof"`
}

func (*FrequentFlierAccountEvent_AccountCreated) isFrequentFlierAccountEvent_EventType() {}

func (*FrequentFlierAccountEvent_StatusMatched) isFrequentFlierAccountEvent_EventType() {}

func (*FrequentFlierAccountEvent_PromotedToGoldStatus) isFrequentFlierAccountEvent_EventType() {}

func (*FrequentFlierAccountEvent_FlightTaken) isFrequentFlierAccountEvent_EventType() {}

type FrequentFlierAccountCreated struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AccountId         string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OpeningMiles      int32                  `protobuf:"varint,2,opt,name=opening_miles,json=openingMiles,proto3" json:"opening_miles,omitempty"`
	OpeningTierPoints int32                  `protobuf:"varint,3,opt,name=opening_tier_points,json=openingTierPoints,proto3" json:"opening_tier_points,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FrequentFlierAccountCreated) Reset() {
	*x = FrequentFlierAccountCreated{}
	mi := &file_frequent_flier_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrequentFlierAccountCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrequentFlierAccountCreated) ProtoMessage() {}

func (x *FrequentFlierAccountCreated) ProtoReflect() protoreflect.Message {
	mi := &file_frequent_flier_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrequentFlierAccountCreated.ProtoReflect.Descriptor instead.
func (*FrequentFlierAccountCreated) Descriptor() ([]byte, []int) {
	return file_frequent_flier_account_proto_rawDescGZIP(), []int{1}
}

func (x *FrequentFlierAccountCreated) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *FrequentFlierAccountCreated) GetOpeningMiles() int32 {
	if x != nil {
		return x.OpeningMiles
	}
	return 0
}

func (x *FrequentFlierAccountCreated) GetOpeningTierPoints() int32 {
	if x != nil {
		return x.OpeningTierPoints
	}
	return 0
}

type StatusMatched struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewStatus     Status                 `protobuf:"varint,1,opt,name=new_status,json=newStatus,proto3,enum=Status" json:"new_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusMatched) Reset() {
	*x = StatusMatched{}
	mi := &file_frequent_flier_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusMatched) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusMatched) ProtoMessage() {}

func (x *StatusMatched) ProtoReflect() protoreflect.Message {
	mi := &file_frequent_flier_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusMatched.ProtoReflect.Descriptor instead.
func (*StatusMatched) Descriptor() ([]byte, []int) {
	return file_frequent_flier_account_proto_rawDescGZIP(), []int{2}
}

func (x *StatusMatched) GetNewStatus() Status {
	if x != nil {
		return x.NewStatus
	}
	return Status_STATUS_UNSPECIFIED
}

// Newly added event
type FlightTaken struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MilesAdded      int32                  `protobuf:"varint,1,opt,name=miles_added,json=milesAdded,proto3" json:"miles_added,omitempty"`
	TierPointsAdded int32                  `protobuf:"varint,2,opt,name=tier_points_added,json=tierPointsAdded,proto3" json:"tier_points_added,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FlightTaken) Reset() {
	*x = FlightTaken{}
	mi := &file_frequent_flier_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightTaken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightTaken) ProtoMessage() {}

func (x *FlightTaken) ProtoReflect() protoreflect.Message {
	mi := &file_frequent_flier_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightTaken.ProtoReflect.Descriptor instead.
func (*FlightTaken) Descriptor() ([]byte, []int) {
	return file_frequent_flier_account_proto_rawDescGZIP(), []int{3}
}

func (x *FlightTaken) GetMilesAdded() int32 {
	if x != nil {
		return x.MilesAdded
	}
	return 0
}

func (x *FlightTaken) GetTierPointsAdded() int32 {
	if x != nil {
		return x.TierPointsAdded
	}
	return 0
}

type PromotedToGoldStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromotedToGoldStatus) Reset() {
	*x = PromotedToGoldStatus{}
	mi := &file_frequent_flier_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromotedToGoldStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotedToGoldStatus) ProtoMessage() {}

func (x *PromotedToGoldStatus) ProtoReflect() protoreflect.Message {
	mi := &file_frequent_flier_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotedToGoldStatus.ProtoReflect.Descriptor instead.
func (*PromotedToGoldStatus) Descriptor() ([]byte, []int) {
	return file_frequent_flier_account_proto_rawDescGZIP(), []int{4}
}

var File_frequent_flier_account_proto protoreflect.FileDescriptor

var file_frequent_flier_account_proto_rawDesc = string([]byte{
	0x0a, 0x1c, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x6c, 0x69, 0x65, 0x72,
	0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xae,
	0x02, 0x0a, 0x19, 0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x74, 0x46, 0x6c, 0x69, 0x65, 0x72,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x47, 0x0a, 0x0f,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x74,
	0x46, 0x6c, 0x69, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x37, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x48, 0x00, 0x52,
	0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x12, 0x4e,
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x6f, 0x5f, 0x67, 0x6f,
	0x6c, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x65, 0x64, 0x54, 0x6f, 0x47, 0x6f, 0x6c, 0x64,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x14, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74,
	0x65, 0x64, 0x54, 0x6f, 0x47, 0x6f, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x31,
	0x0a, 0x0c, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x74, 0x61, 0x6b, 0x65, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x54, 0x61, 0x6b,
	0x65, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x54, 0x61, 0x6b, 0x65,
	0x6e, 0x42, 0x0c, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22,
	0x91, 0x01, 0x0a, 0x1b, 0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x74, 0x46, 0x6c, 0x69, 0x65,
	0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x69, 0x6c, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x4d, 0x69,
	0x6c, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x74,
	0x69, 0x65, 0x72, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x11, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x65, 0x72, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x22, 0x37, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x0a, 0x6e, 0x65, 0x77, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5a, 0x0a, 0x0b,
	0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x54, 0x61, 0x6b, 0x65, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x6d,
	0x69, 0x6c, 0x65, 0x73, 0x5f, 0x61, 0x64, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x6d, 0x69, 0x6c, 0x65, 0x73, 0x41, 0x64, 0x64, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x11,
	0x74, 0x69, 0x65, 0x72, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x5f, 0x61, 0x64, 0x64, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x74, 0x69, 0x65, 0x72, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x41, 0x64, 0x64, 0x65, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x6d,
	0x6f, 0x74, 0x65, 0x64, 0x54, 0x6f, 0x47, 0x6f, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x2a, 0x54, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x52, 0x45, 0x44,
	0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x49, 0x4c,
	0x56, 0x45, 0x52, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x47, 0x4f, 0x4c, 0x44, 0x10, 0x03, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65, 0x68, 0x68, 0x69, 0x6c, 0x66, 0x65, 0x2f, 0x70, 0x62,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x69, 0x6e, 0x67, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_frequent_flier_account_proto_rawDescOnce sync.Once
	file_frequent_flier_account_proto_rawDescData []byte
)

func file_frequent_flier_account_proto_rawDescGZIP() []byte {
	file_frequent_flier_account_proto_rawDescOnce.Do(func() {
		file_frequent_flier_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frequent_flier_account_proto_rawDesc), len(file_frequent_flier_account_proto_rawDesc)))
	})
	return file_frequent_flier_account_proto_rawDescData
}

var file_frequent_flier_account_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_frequent_flier_account_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_frequent_flier_account_proto_goTypes = []any{
	(Status)(0),                         // 0: Status
	(*FrequentFlierAccountEvent)(nil),   // 1: FrequentFlierAccountEvent
	(*FrequentFlierAccountCreated)(nil), // 2: FrequentFlierAccountCreated
	(*StatusMatched)(nil),               // 3: StatusMatched
	(*FlightTaken)(nil),                 // 4: FlightTaken
	(*PromotedToGoldStatus)(nil),        // 5: PromotedToGoldStatus
}
var file_frequent_flier_account_proto_depIdxs = []int32{
	2, // 0: FrequentFlierAccountEvent.account_created:type_name -> FrequentFlierAccountCreated
	3, // 1: FrequentFlierAccountEvent.status_matched:type_name -> StatusMatched
	5, // 2: FrequentFlierAccountEvent.promoted_to_gold_status:type_name -> PromotedToGoldStatus
	4, // 3: FrequentFlierAccountEvent.flight_taken:type_name -> FlightTaken
	0, // 4: StatusMatched.new_status:type_name -> Status
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_frequent_flier_account_proto_init() }
func file_frequent_flier_account_proto_init() {
	if File_frequent_flier_account_proto != nil {
		return
	}
	file_frequent_flier_account_proto_msgTypes[0].OneofWrappers = []any{
		(*FrequentFlierAccountEvent_AccountCreated)(nil),
		(*FrequentFlierAccountEvent_StatusMatched)(nil),
		(*FrequentFlierAccountEvent_PromotedToGoldStatus)(nil),
		(*FrequentFlierAccountEvent_FlightTaken)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frequent_flier_account_proto_rawDesc), len(file_frequent_flier_account_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_frequent_flier_account_proto_goTypes,
		DependencyIndexes: file_frequent_flier_account_proto_depIdxs,
		EnumInfos:         file_frequent_flier_account_proto_enumTypes,
		MessageInfos:      file_frequent_flier_account_proto_msgTypes,
	}.Build()
	File_frequent_flier_account_proto = out.File
	file_frequent_flier_account_proto_goTypes = nil
	file_frequent_flier_account_proto_depIdxs = nil
}
